spring:
  
 application:
    name: GATEWAY-SERVICE
    
server:
  port: 8089
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8766/eureka/
  instance:
    hostname: localhost
